apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-fx
  name: app-fx
  namespace: app-fx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-fx
  template:
    metadata:
      labels:
        app: app-fx
    spec:
      containers:
      - image: nginx
        name: nginx
