apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: scale-to-zero
spec:
  generateExisting: true
  rules:
    - name: scale-to-zero
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
      exclude:
        any:
          - resources:
              namespaces:
                - default
      generate:
        synchronize: true
        apiVersion: keda.sh/v1alpha1
        kind: ScaledObject
        namespace: "{{request.object.metadata.namespace}}"
        name: "scale-to-zero-{{request.object.metadata.name}}"
        data:
          spec:
            minReplicaCount: 0
            pollingInterval: 10
            cooldownPeriod: 20
            scaleTargetRef:
              name: "{{request.object.metadata.name}}"
              apiVersion: apps/v1
              kind: "{{request.object.kind}}"
            triggers:
              - type: cron
                metadata:
                  timezone: Europe/London
                  start: 09 * * * *
                  end: 15 * * * *
                  desiredReplicas: "{{ to_string(request.object.spec.replicas) }}"
