apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scale-to-zero-kyverno
  namespace: kyverno
  # annotations: 
    # autoscaling.keda.sh/paused-replicas: "3"
spec:
  minReplicaCount: 0
  maxReplicaCount: 3
  pollingInterval: 10
  cooldownPeriod: 20
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
  triggers:
    - type: cron
      metadata:
        timezone: Europe/London
        start: 18 * * * *
        end: 20 * * * *
        desiredReplicas: "1"
